### PR TITLE
[INLONG-1507]Fix Go SDK connection pool bug.

### LINKED ISSUE #1507: Go Client should reconnect to server if the server is shutdown and restarted
#### Expected behavior

Tell us what should happen
Go client should reconnect to server
#### Actual behavior

Tell us what happens instead
Go client doesn't reconnect to server
#### Steps to reproduce

How can we reproduce the issue
We can connect to server with go client. Then we shutdown the tubemq server and restart it.
#### System configuration
**InLong version**: x.y

### PR DESCRIPTION
**Pull request by TszKitLo40**
Signed-off-by: Zijie Lu <wslzj40@gmail.com>

### Title Name: [INLONG-1507][component] Title of the pull request

where *XYZ* should be replaced by the actual issue number.

Fixes #1507 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: tubemq-client-twins/tubemq-client-go/multiplexing/multiplexing.go [hunk 1]
```diff
@@ -84,29 +85,42 @@ func (p *Pool) Get(ctx context.Context, address string, serialNo uint32, opts *D
...
 	}
+	p.mu.Lock()
+	// If the concurrent request has created the connection, the connection can be returned directly.
+	if v, ok := p.connections.Load(address); ok {
+		if c, ok := v.(*Connection); ok {
+			mc, err := c.new(ctx, serialNo)
+			p.mu.Unlock()
+			return mc, err
+		}
+		p.mu.Unlock()
```
Comment (charlely) [inline tubemq-client-twins/tubemq-client-go/multiplexing/multiplexing.go:96]: This Unlock function need use defer to release.

**Review by gosonzhang — APPROVED** [review]
+1
