### PR TITLE
[INLONG-3228][Manager] Deadlock found when trying to get lock

### LINKED ISSUE #3228: [Bug][Manager] Deadlock found when trying to get lock
### What happened

Error log:

```
2022-03-18 10:08:56.153 [http-nio-8083-exec-51] ERROR o.a.i.m.web.config.ControllerExceptionHandler:124 - 
Failed to handle request on path:/api/inlong/manager/openapi/agent/reportAndGetTask
org.springframework.dao.DeadlockLoserDataAccessException: 
### Error querying database.  Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
### The error may exist in class path resource [mappers/StreamSourceEntityMapper.xml]
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: select id, inlong_group_id, inlong_stream_id, source_type, source_name, agent_ip, uuid,
         server_id, server_name, cluster_id, cluster_name, snapshot, report_time, ext_params,
         status, previous_status, is_deleted, creator, modifier, create_time, modify_time
         from stream_source
         WHERE is_deleted = 0
         and status in (?, ?)limit 2 for update
### Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction;
Deadlock found when trying to get lock; try restarting transaction; nested exception is com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: 
Deadlock found when trying to get lock; try restarting transaction
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:271)
```

### What you expected to happen

Should not error.

### How to reproduce

After the stream source has been issued, just restart it, you may find the error.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by healchow**
### Title Name: [INLONG-3228][Manager] Deadlock found when trying to get lock

Fixes #3228 

### Motivation

Deadlock found when trying to get lock.

### Modifications

1. Not use `select for update` when querying sources by related id.

2. Add some logs.

### Verifying this change

- [X] Make sure that the change passes the CI checks.

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java [hunk 1]
```diff
@@ -112,7 +112,7 @@ public Boolean reportSnapshot(TaskSnapshotRequest request) {
     @Override
     @Transactional(rollbackFor = Throwable.class, isolation = Isolation.REPEATABLE_READ)
```
Comment (gong) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:113]: why not to modify `Isolation.REPEATABLE_READ` to `Isolation.READ_COMMITTED`

Comment (healchow) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AgentServiceImpl.java:113]: Because the inner method `getTaskResult` needs `Isolation.READ_COMMITTED`.

**Review by dockerzhang — APPROVED** [review]

**Review by chestnut-c — APPROVED** [review]
