### PR TITLE
[INLONG-4453][Sort-Standalone] Fix bug that report wrong audit when send to kafka failed

### LINKED ISSUE #4453: [Bug][Sort-Standalone] Wrong audit when send to kafka failed
### What happened

1. miss the channel exception when put events to channel
2. miss prese fail audit when parese events to kafka producer record
3. wrong audit when send to kafka failed

### What you expected to happen

fix them

### How to reproduce

1. when channel is full
2. when parse event failed
3. when send data to kafka failed

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by vernedeng**
### Title Name: [INLONG-4453][Sort-Standalone] Fix bug that report wrong audit when send to kafka failed

Fixes #4453 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve?*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationWorker.java [hunk 1]
```diff
@@ -117,7 +112,7 @@ public void run() {
             } catch (Exception e) {
                 LOG.error(e.getMessage(), e);
                 if (tx != null) {
-                    tx.rollback();
+                    tx.commit();
```
Comment (luchunliang) [inline inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationWorker.java:115]: When it is fail to send data to Kafka, here need to rollback transaction.

Comment (vernedeng) [reply inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/kafka/KafkaFederationWorker.java]: fixed

**Review by luchunliang — APPROVED** [review]
LGTM

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
