### PR TITLE
[INLONG-2263] SortStandalone get metric value with error JMX ObjectName

### LINKED ISSUE #2263: [Bug] SortStandalone get metric value with error JMX ObjectName
### What happened

SortStandalone get metric value with error JMX ObjectName

### What you expected to happen

SortStandalone get metric value with error JMX ObjectName

### How to reproduce

SortStandalone get metric value with error JMX ObjectName

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luchunliang**
### Title Name: [INLONG-2263][Inlong-SortStandalone] SortStandalone get metric value with error JMX ObjectName

Fixes #2263 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

File: inlong-sort-standalone/sort-standalone-common/src/test/java/org/apache/inlong/sort/standalone/metrics/TestMetricListenerRunnable.java [hunk 1]
```diff
@@ -0,0 +1,152 @@
...
+import org.apache.inlong.commons.config.metrics.MetricUtils;
+import org.apache.inlong.commons.config.metrics.MetricValue;
+import org.junit.BeforeClass;
+import org.junit.Test;
+
+/**
+ * 
+ * TestMetricItemSetMBean
+ */
+public class TestMetricListenerRunnable {
```
Comment (healchow) [inline inlong-sort-standalone/sort-standalone-common/src/test/java/org/apache/inlong/sort/standalone/metrics/TestMetricListenerRunnable.java:36]: It is recommended to add "Test" after the tested class name, add "test" before the tested method name.

Comment (luchunliang) [reply inlong-sort-standalone/sort-standalone-common/src/test/java/org/apache/inlong/sort/standalone/metrics/TestMetricListenerRunnable.java:36]: "Test" is prefix of class name in history TestCase.
It is same in hadoop and hive.
image
image

Comment (healchow) [reply inlong-sort-standalone/sort-standalone-common/src/test/java/org/apache/inlong/sort/standalone/metrics/TestMetricListenerRunnable.java:36]: Fine. It looks like each project has its style.

BTW, we need to formulate the specification of InLong in a future version.

**Review by healchow — APPROVED** [review]
