### PR TITLE
[INLONG-2793][Sort] Fix bugs related to hive sink

### LINKED ISSUE #2793: [Bug][Sort] Bugs related to hive sink
### What happened

1. Missing '/' when creating path;
2. TextFileFormat json deserialization

### What you expected to happen

No bug

### How to reproduce

Start a single-tenant job.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by KevinWen007**
### Title Name: [INLONG-2793][Sort] Fix bugs related to hive sink

Fixes #2793 

### Motivation

Fix bugs related to hive sink:
1. Missing '/' when creating path;
2. TextFileFormat json deserialization

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### CODE REVIEW

File: inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/filesystem/Bucket.java [hunk 1]
```diff
@@ -89,7 +89,13 @@ private Bucket(
         this.fsWriter = checkNotNull(fsWriter);
         this.subtaskIndex = subtaskIndex;
         this.bucketId = checkNotNull(bucketId);
-        this.bucketPath = checkNotNull(bucketPath);
+
+        String bucketPathStr = checkNotNull(bucketPath).toString();;
```
Comment (healchow) [inline inlong-sort/sort-connectors/src/main/java/org/apache/inlong/sort/flink/filesystem/Bucket.java:93]: Why two `;`?

**Review by chantccc — APPROVED** [review]
+1

**Review by dockerzhang — APPROVED** [review]
