### PR TITLE
[INLONG-2931][Manager] Improve parse response in manager client

### LINKED ISSUE #2931: [Improve] Fix class convert exception in Manager
### Description

_No response_

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kipshi**
### Title Name: [INLONG-2931][Manager] Improve parse response in manager client

Fixes #2931 

### Verifying this change

- [X] Make sure that the change passes the CI checks.

### CODE REVIEW

File: inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java [hunk 1]
```diff
@@ -109,6 +114,30 @@ public static InlongStreamInfo parseStreamInfo(Response response) {
...
+            JsonArray sourceJsonArr = fullStreamJson.getAsJsonArray(SOURCE_INFO);
+            List<SourceResponse> sourceResponses = Lists.newArrayList();
+            fullStreamResponse.setSourceInfo(sourceResponses);
+            for (int j = 0; j < sourceJsonArr.size(); j++) {
+                JsonObject sourceJson = (JsonObject) sourceJsonArr.get(i);
+                String type = sourceJson.get(SOURCE_TYPE).getAsString();
+                SourceType sourceType = SourceType.forType(type);
+                switch (sourceType) {
+                    case BINLOG:
+                        BinlogSourceResponse hiveSinkResponse = GsonUtil.fromJson(sourceJson.toString(),
```
Comment (healchow) [inline inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java:127]: Maybe this variable can name `binlogSourceResponse`?

Comment (kipshi) [reply inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongParser.java:127]: yes

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
