### PR TITLE
[INLONG-3335][Agent] Fix agent snapshot mode won't work and optimize jvm parameters

### LINKED ISSUE #3335: [Bug] fix agent snapshot mode won't work and optimize jvm parameters
### What happened

[Bug] fix agent snapshot mode won't work and optimize jvm parameters

### What you expected to happen

[Bug] fix agent snapshot mode won't work and optimize jvm parameters

### How to reproduce

[Bug] fix agent snapshot mode won't work and optimize jvm parameters

### Environment

_No response_

### InLong version

0.12.0

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EMsnap**
### Title Name: [INLONG-3335][Agent] Fix agent snapshot mode won't work and optimize jvm parameters

Fixes #3335 

### Motivation

Fix agent snapshot mode won't work and optimize jvm parameters

### Modifications

Fix agent snapshot mode won't work and optimize jvm parameters

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

### Documentation

  - Does this pull request introduce a new feature? (no)

### CODE REVIEW

File: inlong-agent/bin/agent-env.sh [hunk 1]
```diff
@@ -36,7 +36,7 @@ else
   export JPS="$JAVA_HOME/bin/jps"
 fi
 
-HEAP_OPTS="-Xmx1024m -Xms512m"
+HEAP_OPTS="-Xmx7168m -Xms7168m"
```
Comment (dockerzhang) [inline inlong-agent/bin/agent-env.sh:39]: this size is too large for docker, we should make the default value more appropriately.

Comment (EMsnap) [reply inlong-agent/bin/agent-env.sh]: done

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
