### PR TITLE
[INLONG-2662][Manager] Fix bug to avoid reinit of service task

### LINKED ISSUE #2662: [Bug] Fix duplicate listener in manager service
### What happened

When init workflow definition, in some cases,  duplicate listener will be added in service task;

### What you expected to happen

When init workflow definition, in some cases,  no duplicate listener will be added in service task;

### How to reproduce

Create workflow twice , than will find exception be throwed;

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kipshi**
### Title Name: [INLONG-2662][Manager] Fix bug to avoid reinit of service task

Fixes #2662 

### Verifying this change

- [X] Make sure that the change passes the CI checks.

This change is a trivial rework/code cleanup without any test coverage.

### Documentation

  - Does this pull request introduces a new feature? no

### CODE REVIEW

File: inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/ServiceTask.java [hunk 1]
```diff
@@ -42,6 +44,8 @@
 
     private ServiceTaskType serviceTaskType;
 
+    private boolean isInit;
```
Comment (gosonzhang) [inline inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/ServiceTask.java:47]: For isInit

If there is multi-threaded access, it is recommended to add volatile define. If there is a multi-threaded concurrent modification, at least a lock is required to avoid reentrancy

Comment (kipshi) [reply inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/ServiceTask.java:47]: Excellent comment !!

Comment (kipshi) [reply inlong-manager/manager-workflow/src/main/java/org/apache/inlong/manager/workflow/definition/ServiceTask.java]: I prefer to use CAS to avoid multi-thread modification like this;

private AtomicBoolean isInit = new AtomicBoolean(false);

public void initListeners(WorkflowContext workflowContext) {
        if (isInit.compareAndSet(false, true)) {
            if (listenerProvider == null || serviceTaskType == null) {
                return;
            }
            Iterable<TaskEventListener> listeners = listenerProvider.get(workflowContext, serviceTaskType);
            addListeners(Lists.newArrayList(listeners));
        } else {
            log.debug("ServiceTask:{} is already init", getName());
        }
    }

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
