### PR TITLE
[INLONG-3083][Agent] Agent should update scala version in kafka client, and commit offset when read finish

### LINKED ISSUE #3083: [Bug][Agent] Upgrade Scala version in Kafka client, and commit offset when reading finish
### What happened

[Bug] Agent should update scala version in kafka client, and commit offset when read finish

### What you expected to happen

[Bug] Agent should update scala version in kafka client, and commit offset when read finish

### How to reproduce

[Bug] Agent should update scala version in kafka client, and commit offset when read finish

### Environment

[Bug] Agent should update scala version in kafka client, and commit offset when read finish

### InLong version

0.12.0

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by EMsnap**
### Title Name: [INLONG-XYZ][component] Title of the pull request

where *XYZ* should be replaced by the actual issue number.

Fixes #3083 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestKafkaReader.java [hunk 1]
```diff
@@ -63,5 +64,6 @@ public void testKafkaReader() {
         } catch (Exception e) {
             LOGGER.error("get record failed:", e);
         }
+        AgentUtils.silenceSleepInMs(100000);
```
Comment (healchow) [inline inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestKafkaReader.java:67]: Do unit tests need to wait so long?

Comment (EMsnap) [reply inlong-agent/agent-plugins/src/test/java/org/apache/inlong/agent/plugin/sources/TestKafkaReader.java]: test code, removed, pls check

**Review by dockerzhang — APPROVED** [review]

**Review by gosonzhang — APPROVED** [review]
