### PR TITLE
[INLONG-4388][Manager] Change Elasticsearch scaling_factor use correct mapping info

### LINKED ISSUE #4388: [Bug][Manager] Elasticsearch create command scaling_factor use wrong mapping info
### What happened

Scaling_factor information use wrong mapping info, it is using format info.

### What you expected to happen

Scaling_factor information use scaling_factor mapping info not format info.

### How to reproduce

Scaling_factor information use scaling_factor mapping info not format info.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by lucaspeng12138**
### Title Name: [INLONG-4388][Manager] Change Elasticsearch scaling_factor use correct mapping info

Elasticsearch scaling_factor used format info, it's wrong. Fix this problem.

Fixes #4388 

### Motivation

Elasticsearch scaling_factor used format info, it's wrong.

### Modifications

Change scaling_factor uses correct information.

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/es/ElasticsearchApi.java [hunk 1]
```diff
@@ -133,10 +133,10 @@ private List<String> getMappingInfo(List<ElasticsearchFieldInfo> fieldsInfo) {
                     fieldStr.append(",\n          \"format\" : \"")
                             .append(entry.getFormat()).append("\"");
                 }
-            } else if (entry.getType().contains("float")) {
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/es/ElasticsearchApi.java:136]: Suggested change the `entry` to `field`.

**Review by healchow — CHANGES_REQUESTED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/es/ElasticsearchApi.java (hunk 1 above)
Comment (lucaspeng12138) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/resource/es/ElasticsearchApi.java:136]: fixed

**Review by healchow — APPROVED** [review]

**Comment by healchow** [comment]
Please rebase from the master after the #4391 merged.

**Review by dockerzhang — APPROVED** [review]
