### PR TITLE
[INLONG-4315][Manager] Fix incorrect task service node order in create-group workflow

### LINKED ISSUE #4315: [Bug][Manager] Incorrect task service node order in create-group workflow
### What happened

The sort task service node is before the sink resource node, which seems incorrect. 

### What you expected to happen

The sort task depends on the resources so the resources must be created first. The correct order should be: init_source -> init_mq -> init_sink -> config/start sort

### How to reproduce

Delay the sink resource creation processing time.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by woofyzhao**
Fixes #4315

### CODE REVIEW

**Review by healchow — CHANGES_REQUESTED** [review]
Please update the order in `CreateStreamWorkflowDefinition` together.

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/CreateGroupWorkflowDefinition.java [hunk 1]
```diff
@@ -85,14 +85,6 @@ public WorkflowProcess defineProcess() {
         initMQResourceTask.addListenerProvider(groupTaskListenerFactory);
         process.addTask(initMQResourceTask);
 
-        // init Sort resource
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/CreateGroupWorkflowDefinition.java:88]: We need to adjust the order of creating resources to 1. MQ -> 2. Sink -> 3. Sort -> 4. Source, so as to ensure that after some links fail, data will not be collected or consumed.

**Review by healchow — CHANGES_REQUESTED** [review]

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/CreateGroupWorkflowDefinition.java (hunk 1 above)
Comment (woofyzhao) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/workflow/group/CreateGroupWorkflowDefinition.java]: Understood.

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by gong — APPROVED** [review]
