### PR TITLE
[INLONG-4095][Manager] Fix UT error and align special characters

### LINKED ISSUE #4095: [Bug][Manager] Managerctl unit test error and characters are not aligned
### What happened

1.Managerctl UT error.

image

2.Run `list group` table is misplaced when it contains Chinese characters.

image

### What you expected to happen

No UT errors and alignment fields.

### How to reproduce

1.Run unit tests.

2.Run `list group`.

### Environment

_No response_

### InLong version

0.12.0

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by haifxu**
### Title Name: [INLONG-XYZ][component] Fix UT error and align special characters

Fixes #4095 

### Modifications

1、Modify the configuration file acquisition method

2、Add judgment to special characters

### Verifying this change

image

### CODE REVIEW

File: inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandUtil.java [hunk 1]
```diff
@@ -25,22 +25,24 @@
...
+import java.nio.file.Paths;
 import java.util.Properties;
 
 abstract class CommandUtil {
 
     public InlongClientImpl connect() {
         Properties properties = new Properties();
-        String path = System.getProperty("user.dir") + "/conf/application.properties";
+        String path =
+                Thread.currentThread().getContextClassLoader().getResource("").getPath() + "application.properties";
```
Comment (healchow) [inline inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/CommandUtil.java:42]: Could you please set the `application.properties` as a constant?

File: inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/util/PrintUtil.java [hunk 2]
```diff
@@ -17,13 +17,14 @@
 
 package org.apache.inlong.manager.client.cli.util;
 
+import com.alibaba.fastjson.JSONObject;
```
Comment (healchow) [inline inlong-manager/manager-client-tools/src/main/java/org/apache/inlong/manager/client/cli/util/PrintUtil.java:20]: Please replace the `fastjson` with the `gson`.

**Review by healchow — APPROVED** [review]

**Review by kipshi — APPROVED** [review]
