### PR TITLE
[INLONG-3168][Agent] Change the deserialization type from String to byte array

### LINKED ISSUE #3168: [Bug][Agent] modify deserializerType
### What happened

modify deserializerType

### What you expected to happen

modify deserializerType

### How to reproduce

modify deserializerType

### Environment

_No response_

### InLong version

0.12.0

### InLong Component

InLong Agent

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by zk1510**
[INLONG-3168][Agent] modify deserializerType

Fixes #3168

### Motivation

modify deserializerType

### Modifications

modify deserializerType

### CODE REVIEW

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

File: inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/KafkaReader.java [hunk 1]
```diff
@@ -133,12 +131,13 @@ public Message read() {
                 headerMap.put("record.offset", String.valueOf(record.offset()));
                 headerMap.put("record.key", String.valueOf(record.key()));
                 LOGGER.info(
-                        "partition:" + record.partition() + "value:" + recordValue + ", offset:" + record.offset());
+                        "partition:" + record.partition()
```
Comment (EMsnap) [inline inlong-agent/agent-plugins/src/main/java/org/apache/inlong/agent/plugin/sources/reader/KafkaReader.java:134]: make it debug, would cost a lot of space if each record is printed

**Review by EMsnap — COMMENTED** [review]
what's the purpose of changing it to byte array?

**Review by EMsnap — APPROVED** [review]
