### PR TITLE
[INLONG-2684][Sort] Fix OOM for sort sdk unit test

### LINKED ISSUE #2684: [Bug] fix sort sdk UT OOM bug
### What happened

image

### What you expected to happen

may be powermockito and maven-surefire-plugin problems

### How to reproduce

https://github.com/apache/incubator-inlong/runs/5302880922?check_suite_focus=true

### Environment

_No response_

### InLong version

1.0.0

### InLong Component

InLong SDK

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wardlican**
### Title Name: [INLONG-2684][Sort] Fix OOM for sort sdk unit test

Fixes #2684

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [X] Make sure that the change passes the CI checks.

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)

### CODE REVIEW

**Review by dockerzhang — APPROVED** [review]

File: inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/InLongPulsarFetcherImplTest.java [hunk 1]
```diff
@@ -42,42 +43,51 @@
...
         inLongTopic.setPartitionId(0);
         inLongTopic.setTopicType("pulsar");
 
         CacheZoneCluster cacheZoneCluster = new CacheZoneCluster("clusterId", "bootstraps", "token");
         inLongTopic.setInLongCluster(cacheZoneCluster);
-        clientContext = PowerMockito.mock(ClientContext.class);
+        try {
+            clientContext = PowerMockito.mock(ClientContext.class);
+        } catch (Exception e) {
+            e.printStackTrace();
```
Comment (healchow) [inline inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/InLongPulsarFetcherImplTest.java:77]: Please not try-catch the mock exception in the unit test. If necessary, you can use the Assert to judge exceptions.

Comment (wardlican) [reply inlong-sdk/sort-sdk/src/test/java/org/apache/inlong/sdk/sort/impl/InLongPulsarFetcherImplTest.java:77]: ok I will fix it in next version

**Review by healchow — APPROVED** [review]
