### PR TITLE
[INLONG-2934][Manager] Manager client occured NPE since not check NUL

### LINKED ISSUE #2934: [Bug][Manager] Manager client occured NPE since not check NULL
### What happened

failed when null

### What you expected to happen

pass when null

### How to reproduce

fault tolerance

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by ciscozhou**
### Title Name: [INLONG-2934][Manager]Manager client occured NPE since not check NUL

where *XYZ* should be replaced by the actual issue number.

Fixes #2934 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java [hunk 1]
```diff
@@ -192,10 +193,14 @@ private static BinlogSourceRequest createBinlogSourceRequest(MySQLBinlogSource b
         sourceRequest.setServerTimezone(binlogSource.getServerTimezone());
         sourceRequest.setMonitoredDdl(binlogSource.getMonitoredDdl());
         sourceRequest.setAllMigration(binlogSource.isAllMigration());
-        String dbNames = Joiner.on(",").join(binlogSource.getDbNames());
-        sourceRequest.setDatabaseWhiteList(dbNames);
-        String tableNames = Joiner.on(",").join(binlogSource.getTableNames());
-        sourceRequest.setTableWhiteList(tableNames);
+        if (!CollectionUtils.isEmpty(binlogSource.getDbNames())) {
```
Comment (healchow) [inline inlong-manager/manager-client/src/main/java/org/apache/inlong/manager/client/api/util/InlongStreamSourceTransfer.java:196]: Please use `CollectionUtils.isNotEmpty` under the commons packages.

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
