### PR TITLE
[INLONG-4591][Sort] Set the default hive version and alter the log version from log4j to log4j2 in the sort core module

### LINKED ISSUE #4591: [Bug][Sort] Set the default hive version and alter the log version from log4j to log4j2 in the sort core module
### What happened

An error occurs when the user omits an incoming version

### What you expected to happen

Set the default Hive version in the protocol

### How to reproduce

hive version param is null

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Sort

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GanfengTan**
An error occurs when the user omits an incoming version, data sink hive.
Alter log version module of sort core.

- Fixes #4591 

### Motivation

Test error.

### Modifications

Set default version 3.1.2.
Change log version  from log4j to log4j2.

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HiveLoadNode.java [hunk 1]
```diff
@@ -99,7 +99,7 @@ public HiveLoadNode(@JsonProperty("id") String id,
         this.database = Preconditions.checkNotNull(database, "database of hive is null");
         this.tableName = Preconditions.checkNotNull(tableName, "table of hive is null");
         this.hiveConfDir = hiveConfDir;
-        this.hiveVersion = hiveVersion;
+        this.hiveVersion = null == hiveVersion ? "3.1.2" : hiveVersion;
```
Comment (EMsnap) [inline inlong-sort/sort-common/src/main/java/org/apache/inlong/sort/protocol/node/load/HiveLoadNode.java:102]: please extract 3.1.2 as constant

**Review by thexiay — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
