### PR TITLE
[INLONG-3332][Sort-Standalone] Fix NP and data race in ClsSink

### LINKED ISSUE #3332: [Bug][Sort-Standalone] NP when init ClsSink and data race problem when first get ClsIdConfig field list
### What happened

1. NP when init deletingClients and ClsWorkers
2. data race in ClsIdConfig, result in unexpected keyList

### What you expected to happen

1. init deletingClients and ClsWorkers susccessfully
2. only one thread can produce keyList when first time invoke ClsIdConfig::getFieldList

### How to reproduce

Run Sort-Standalone cls sink

### Environment

_No response_

### InLong version

master

### InLong Component

Other for not specified component

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by vernedeng**
### Title Name: [INLONG-3332][Sort-Standalone] Fix NP and data race in ClsSink

Fixes #3332

### Motivation

NP when init deletingClients and ClsWorkers
data race in ClsIdConfig, result in unexpected keyList

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsIdConfig.java [hunk 1]
```diff
@@ -46,10 +46,12 @@
      */
     public List<String> getFieldList() {
         if (fieldList == null) {
-            this.fieldList = new ArrayList<>();
-            if (fieldNames != null) {
-                String[] fieldNameArray = fieldNames.split("\\s+");
-                this.fieldList.addAll(Arrays.asList(fieldNameArray));
+            synchronized (fieldNames) {
```
Comment (luchunliang) [inline inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsIdConfig.java:49]: This line will throw Exception when fieldNames==null.
It is better to invoke this method in reload method.

**Review by luchunliang — APPROVED** [review]

File: inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsIdConfig.java (hunk 1 above)
Comment (vernedeng) [reply inlong-sort-standalone/sort-standalone-source/src/main/java/org/apache/inlong/sort/standalone/sink/cls/ClsIdConfig.java:49]: thx, fixed it

**Review by dockerzhang — APPROVED** [review]
