### PR TITLE
[INLONG-2962][DataProxy] Unit tests throw so many error msg

### LINKED ISSUE #2962: [Bug][UT] Unit tests throw so many error msg for DataProxy
### What happened

In this CI pipeline, there is so many error msg:

```
04:19:39.999 [main] ERROR org.apache.inlong.dataproxy.sink.pulsar.PulsarClientService - create connnection error in metasink, maybe pulsar master set error, please re-check.url127.0.0.1:8080,127.0.0.1:8088, ex1 java.lang.IllegalArgumentException: Illegal character in scheme name at index 0: 127.0.0.1:8080,127.0.0.1:8088
04:20:01.448 [Thread-1] ERROR org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker - exception caught
java.lang.NullPointerException: null
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkRemoteConfig(ConfigManager.java:359) [classes/:?]
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.run(ConfigManager.java:381) [classes/:?]
04:20:10.274 [main] ERROR org.apache.inlong.dataproxy.sink.pulsar.PulsarClientService - create pulsar client has error e = org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: org.apache.pulsar.shade.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:6680 inlongGroupId = null, inlongStreamId= null
04:20:35.700 [Thread-1] ERROR org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker - exception caught
java.lang.NullPointerException: null
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkRemoteConfig(ConfigManager.java:359) [classes/:?]
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.run(ConfigManager.java:381) [classes/:?]
04:20:40.307 [main] ERROR org.apache.inlong.dataproxy.sink.pulsar.PulsarClientService - create pulsar client has error e = org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: org.apache.pulsar.shade.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:6680 inlongGroupId = null, inlongStreamId= null
04:21:10.338 [main] ERROR org.apache.inlong.dataproxy.sink.pulsar.PulsarClientService - create pulsar client has error e = org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: org.apache.pulsar.shade.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:6680 inlongGroupId = null, inlongStreamId= null
04:21:10.609 [Thread-1] ERROR org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker - exception caught
java.lang.NullPointerException: null
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkRemoteConfig(ConfigManager.java:359) [classes/:?]
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.run(ConfigManager.java:381) [classes/:?]
04:21:40.364 [main] ERROR org.apache.inlong.dataproxy.sink.pulsar.PulsarClientService - create pulsar client has error e = org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: org.apache.pulsar.shade.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:6680 inlongGroupId = null, inlongStreamId= null
04:21:46.426 [Thread-1] ERROR org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker - exception caught
java.lang.NullPointerException: null
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.checkRemoteConfig(ConfigManager.java:359) [classes/:?]
	at org.apache.inlong.dataproxy.config.ConfigManager$ReloadConfigWorker.run(ConfigManager.java:381) [classes/:?]
04:22:10.400 [main] ERROR org.apache.inlong.dataproxy.sink.pulsar.PulsarClientService - create pulsar client has error e = org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: org.apache.pulsar.shade.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:6680 inlongGroupId = null, inlongStreamId= null
ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not a subtype
04:22:14.757 [main] ERROR org.apache.inlong.common.metric.MetricRegister - exception while register mbean:org.apache.inlong:type=DataProxy,name=null,error:org.apache.inlong:type=DataProxy,name=null
04:22:14.778 [main] ERROR org.apache.inlong.common.metric.MetricRegister - org.apache.inlong:type=DataProxy,name=null
javax.management.InstanceAlreadyExistsException: org.apache.inlong:type=DataProxy,name=null
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) ~[?:1.8.0_292]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898) ~[?:1.8.0_292]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966) ~[?:1.8.0_292]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) ~[?:1.8.0_292]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) ~[?:1.8.0_292]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[?:1.8.0_292]
	at org.apache.inlong.common.metric.MetricRegister.register(MetricRegister.java:64) [classes/:?]
	at org.apache.inlong.dataproxy.sink.pulsar.federation.PulsarFederationSinkContext.<init>(PulsarFederationSinkContext.java:88) [classes/:?]
	at org.apache.inlong.dataproxy.sink.pulsar.federation.PulsarFederationSink.configure(PulsarFederationSink.java:87) [classes/:?]
	at org.apache.inlong.dataproxy.sink.pulsar.federation.TestPulsarFederationSink.setUp(TestPulsarFederationSink.java:73) [test-classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
```

### What you expected to happen

See in pipeline: https://github.com/apache/incubator-inlong/runs/5443067099?check_suite_focus=truethe 

### How to reproduce

NIL.

### Environment

_No response_

### InLong version

master

### InLong Component

InLong DataProxy

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by luchunliang**
### Title Name: [INLONG-2962][DataProxy] Unit tests throw so many error msg for DataProxy 

Fixes #2962 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [x] Make sure that the change passes the CI checks.

### CODE REVIEW

**Review by healchow — APPROVED** [review]

File: inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java [hunk 1]
```diff
@@ -47,33 +56,42 @@
...
         sink = new PulsarSink();
         channel = new MemoryChannel();
 //        url2token = ConfigManager.getInstance().getThirdPartyClusterUrl2Token();
         Context context = new Context();
         context.put("type", "org.apache.inlong.dataproxy.sink.PulsarSink");
         sink.setChannel(channel);
 
-        Configurables.configure(sink, context);
-        Configurables.configure(channel, context);
+//        Configurables.configure(sink, context);
```
Comment (healchow) [inline inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java:83]: Remove those unused codes.

File: inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java [hunk 2]
```diff
@@ -84,13 +102,13 @@ public void testProcess() throws InterruptedException, EventDeliveryException,
...
 
-        for (int i = 0; i < 5; i++) {
-            Sink.Status status = sink.process();
-            Assert.assertEquals(Sink.Status.READY, status);
-        }
-
-        sink.stop();
-        Assert.assertTrue(LifecycleController.waitForOneOf(sink,
-                LifecycleState.STOP_OR_ERROR, 5000));
+//        for (int i = 0; i < 5; i++) {
```
Comment (healchow) [inline inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java:105]: Remove those unused codes.

File: inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java (hunk 1 above)
Comment (luchunliang) [reply inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java]: removed it

File: inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java (hunk 2 above)
Comment (luchunliang) [reply inlong-dataproxy/dataproxy-source/src/test/java/org/apache/inlong/dataproxy/sink/TestPulsarSink.java]: removed it

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
