### PR TITLE
[INLONG-2066][inlong-tubemq] Confirm the message correctly in Go SDK

### LINKED ISSUE #2066: Each message will be consumed twice.[Bug]
### What happened

Anytime it happens.

### What you expected to happen

The confirmed message should not be consumed again.

### How to reproduce

func main() {
	cfg, err := config.ParseAddress("xxx")
	if err != nil {
		log.Errorf("Failed to parse address", err.Error())
		panic(err)
	}
	c, err := client.NewConsumer(cfg)
	if err != nil {
		log.Errorf("new consumer error %s", err.Error())
		panic(err)
	}
	start := time.Now()
	for {
		elapsed := time.Since(start)
		if elapsed >= 10*time.Minute {
			break
		}
		log.Debug("before GetMessage ")
		crmsg, err := c.GetMessage()
		if err != nil {
			log.Errorf("Get message error %s", err.Error())
			continue
		}
		cr, err := c.Confirm(crmsg.ConfirmContext, true)
		if err != nil {
			log.Errorf("Confirm error %s", err.Error())
			continue
		}
		log.Debug(cr)
		consume(context.Background(), crmsg)
	}
	c.Close()
}

### Environment

centos7

### InLong version

master

### InLong Component

InLong TubeMQ

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by TszKitLo40**
Signed-off-by: Zijie Lu <wslzj40@gmail.com>

### Title Name: [INLONG-XYZ][component] Title of the pull request

where *XYZ* should be replaced by the actual issue number.

Fixes #2066 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*
Message can't be confirmed correctly in Go SDK so that it may be consumed twice.
### Modifications

*Describe the modifications you've done.*
Confirm the message correctly.
### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go [hunk 1]
```diff
@@ -280,7 +280,8 @@ func (c *consumer) Confirm(confirmContext string, consumed bool) (*ConsumerResul
 		return nil, errs.New(errs.RetErrConfirmTimeout, "Not found the partition by confirm_context!")
 	}
 
-	rsp, err := c.sendConfirmReq2Broker(partition)
+	defer c.rmtDataCache.ReleasePartition(true, c.subInfo.IsFiltered(topic), confirmContext, consumed)
```
Comment (gosonzhang) [inline inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go:283]: Sending a confirm request after release is prone to misconfirmation problems:
The partition is released, the second getMessage starts, the first confirm arrives, and the second getMessage is confirmed

**Review by gosonzhang — CHANGES_REQUESTED** [review]

File: inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go (hunk 1 above)
Comment (TszKitLo40) [reply inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go:283]: Partition will be released before leaving this function, so the request will be sent to broker.

Comment (gosonzhang) [reply inlong-tubemq/tubemq-client-twins/tubemq-client-go/client/consumer_impl.go:283]: ye, not a problem. I checked the defer usage of Go, which is similar to the finally approach in Java, it will be called before processing exit.

**Review by gosonzhang — APPROVED** [review]
+1

**Review by dockerzhang — APPROVED** [review]
