### PR TITLE
[INLONG-2723][Manager] Fix batch insert entities error in AbstractService

### LINKED ISSUE #2723: [Bug][Manager] Manager module occurred exception when startup
### What happened

manager will thread exception while starting
wecom-temp-bbb728ff4cd82e2384f7a9dfd079acec

### What you expected to happen

manager will thread exception while starting

### How to reproduce

manager will thread exception while starting

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by baomingyu**
### Title Name: [INLONG-2723][Manager] Fix batch insert entities error in AbstractService

Fixes #2723

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AbstractService.java [hunk 1]
```diff
@@ -102,7 +102,9 @@ public  void run() {
                         }
                         count++;
                     }
-                    batchInsertEntities(entryList);
+                    if (entryList.size() > 0) {
```
Comment (ciscozhou) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AbstractService.java:105]: Its recommanded use `CollectionUtils.isNotEmpty` to check whether a collection is empty or not.

Comment (baomingyu) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/core/impl/AbstractService.java]: CollectionUtils.isNotEmpty  need check more than once.
like this :
coll == null || coll.isEmpty();
 and here entryList is never be null. so check entryList.size()  will be beset.

**Review by healchow — APPROVED** [review]

**Review by dockerzhang — APPROVED** [review]
