### PR TITLE
[INLONG-2963][Manager] Fix get Pulsar url in CommonOperateService

### LINKED ISSUE #2963: [Bug][Manager] Fix get Pulsar url in CommonOperateService
### What happened

Fix get Pulsar url in CommonOperateService

### What you expected to happen

Fix get Pulsar url in CommonOperateService

### How to reproduce

Fix get Pulsar url in CommonOperateService

### Environment

_No response_

### InLong version

master

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by pocozh**
### Title Name: [INLONG-2963][Manager]Fix get Pulsar url in CommonOperateService

Fixes #2963 

### Motivation

*Explain here the context, and why you're making that change. What is the problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Verifying this change

- [ ] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

*(or)*

This change is already covered by existing tests, such as *(please describe tests)*.

*(or)*

This change added tests and can be verified as follows:

*(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java [hunk 1]
```diff
@@ -74,8 +74,12 @@ public String getSpecifiedParam(String key) {
             case Constant.PULSAR_SERVICEURL: {
                 clusterEntity = getThirdPartyCluster(Constant.MIDDLEWARE_PULSAR);
                 if (clusterEntity != null) {
-                    params = gson.fromJson(clusterEntity.getExtParams(), Map.class);
-                    result = params.get(key);
+                    if (key.equals(Constant.PULSAR_SERVICEURL)) {
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java:77]: In the `case` statement, you have already checked the key matches `Constant.PULSAR_SERVICEURL`, so it's recommended to remove this `if`, and do your work in `case Constant.PULSAR_ADMINURL` and `case Constant.PULSAR_SERVICEURL`.

Comment (pocozh) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/CommonOperateService.java]: okkk

**Review by dockerzhang — APPROVED** [review]

**Review by healchow — APPROVED** [review]
