### PR TITLE
[INLONG-3958][Manager] Fix some null pointer exceptions

### LINKED ISSUE #3958: [Improve][Manager] Fix NPEs in manager service
### Description

_No response_

### InLong Component

InLong Manager

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by kipshi**
### Title Name: [INLONG-3958][Manager] Fix NPE in Manager Service

where *XYZ* should be replaced by the actual issue number.

Fixes #3958 

### Verifying this change

*(Please pick either of the following options)*

- [ ] This change is a trivial rework/code cleanup without any test coverage.

- [ ] This change is already covered by existing tests, such as:
  *(please describe tests)*

- [ ] This change added tests and can be verified as follows:

  *(example:)*
  - *Added integration tests for end-to-end deployment with large payloads (10MB)*
  - *Extended integration test for recovery after broker failure*

### Documentation

  - Does this pull request introduce a new feature? (yes / no)
  - If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
  - If a feature is not applicable for documentation, explain why?
  - If a feature is not documented yet in this PR, please create a follow-up issue for adding the documentation

### CODE REVIEW

File: inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java [hunk 1]
```diff
@@ -74,7 +76,10 @@ public static KafkaLoadNode createLoadNode(KafkaSinkResponse kafkaSinkResponse)
                 .map(fieldInfo -> new FieldRelationShip(fieldInfo, fieldInfo)).collect(Collectors.toList());
         Map<String, String> properties = kafkaSinkResponse.getProperties().entrySet().stream()
                 .collect(Collectors.toMap(Map.Entry::getKey, e -> e.getValue().toString()));
-        Integer sinkParallelism = Integer.parseInt(kafkaSinkResponse.getPartitionNum());
+        Integer sinkParallelism = null;
```
Comment (healchow) [inline inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java:79]: If sinkParallelism is null, will it have any effect?

Comment (kipshi) [reply inlong-manager/manager-service/src/main/java/org/apache/inlong/manager/service/sort/util/LoadNodeUtils.java:79]: No effect, sinkParallelism is nullable;

**Review by healchow — APPROVED** [review]

**Review by EMsnap — APPROVED** [review]
